//! Build script for `unitree-dds`.
//!
//! For the Cyclone DDS backend it:
//! 1. compiles the committed idlc-generated topic descriptors (`csrc/*.c`) into
//!    a static lib, using the DDS headers exported by `cyclonedds-sys`
//!    (`DEP_DDSC_INCLUDE_DIR`, available because that crate has `links="ddsc"`);
//! 2. scans those `.c` for `<pkg>_msg_dds__<Name>__desc` symbols and generates
//!    `$OUT_DIR/descriptors.rs` with an `extern "C"` static plus a `CycloneType`
//!    impl for the matching `unitree_msgs` type.
//!
//! The descriptors are committed (generated by `tools/regen-descriptors.sh`
//! with idlc), so a normal build needs only a C compiler — never idlc.

use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

fn main() {
    // Only the Cyclone backend needs the C descriptors.
    if std::env::var_os("CARGO_FEATURE_BACKEND_CYCLONEDDS").is_none() {
        return;
    }

    let manifest_dir = PathBuf::from(env("CARGO_MANIFEST_DIR"));
    let csrc = manifest_dir.join("csrc");
    let out_dir = PathBuf::from(env("OUT_DIR"));

    let include_dir = std::env::var("DEP_DDSC_INCLUDE_DIR")
        .expect("DEP_DDSC_INCLUDE_DIR not set by cyclonedds-sys");

    // Collect committed descriptor C sources.
    let mut c_files: Vec<PathBuf> = fs::read_dir(&csrc)
        .unwrap_or_else(|e| panic!("read_dir {}: {e}", csrc.display()))
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "c"))
        .collect();
    c_files.sort();
    assert!(
        !c_files.is_empty(),
        "no descriptor .c files in {} — run tools/regen-descriptors.sh",
        csrc.display()
    );

    // 1. compile descriptors into a static lib
    let mut build = cc::Build::new();
    build.include(&csrc).include(&include_dir).warnings(false);
    for c in &c_files {
        println!("cargo:rerun-if-changed={}", c.display());
        build.file(c);
    }
    build.compile("unitree_descriptors");

    // 2. generate descriptors.rs from the descriptor symbols
    let mut syms: Vec<String> = Vec::new();
    for c in &c_files {
        let text = fs::read_to_string(c).unwrap();
        collect_desc_symbols(&text, &mut syms);
    }
    syms.sort();
    syms.dedup();

    let mut rs = String::new();
    rs.push_str("// @generated by build.rs from csrc/*.c — do not edit.\n\n");
    for sym in &syms {
        let (pkg, name) = parse_symbol(sym);
        writeln!(rs, "extern \"C\" {{").unwrap();
        writeln!(
            rs,
            "    static {sym}: ::cyclonedds_sys::dds_topic_descriptor_t;"
        )
        .unwrap();
        writeln!(rs, "}}").unwrap();
        writeln!(
            rs,
            "unsafe impl CycloneType for ::unitree_msgs::{pkg}::{name} {{"
        )
        .unwrap();
        writeln!(
            rs,
            "    fn descriptor() -> *const ::cyclonedds_sys::dds_topic_descriptor_t {{ unsafe {{ &{sym} }} }}"
        )
        .unwrap();
        writeln!(rs, "}}\n").unwrap();
    }
    fs::write(out_dir.join("descriptors.rs"), rs).expect("write descriptors.rs");
}

/// Collect `<pkg>_msg_dds__<Name>__desc` identifiers that appear as a
/// `const dds_topic_descriptor_t <sym> =` definition.
fn collect_desc_symbols(text: &str, out: &mut Vec<String>) {
    for line in text.lines() {
        if let Some(idx) = line.find("dds_topic_descriptor_t ") {
            let rest = &line[idx + "dds_topic_descriptor_t ".len()..];
            let sym: String = rest
                .chars()
                .take_while(|c| c.is_alphanumeric() || *c == '_')
                .collect();
            if sym.ends_with("__desc") && sym.contains("_msg_dds__") {
                out.push(sym);
            }
        }
    }
}

/// Split `<pkg>_msg_dds__<Name>__desc` into (`pkg`, `Name`).
fn parse_symbol(sym: &str) -> (&str, &str) {
    let mid = sym.find("_msg_dds__").expect("malformed descriptor symbol");
    let pkg = &sym[..mid];
    let rest = &sym[mid + "_msg_dds__".len()..];
    let name = rest.strip_suffix("__desc").expect("missing __desc suffix");
    (pkg, name)
}

fn env(k: &str) -> String {
    std::env::var(k).unwrap_or_else(|_| panic!("missing env var {k}"))
}
