//! Build script: parse the `.msg` snapshots under `msgs/` and generate, into
//! `$OUT_DIR`:
//!
//! - `generated.rs` — Rust structs for every message with XCDR2
//!   (de)serialization (`CdrSerialize`/`CdrDeserialize`) and `DdsType`.
//! - `idl/<pkg>.idl` — OMG IDL for the "POD" subset (types containing only
//!   scalars / fixed arrays / references to other POD types — i.e. no `string`
//!   and no variable-length sequence). These are the types the Cyclone DDS
//!   backend can exchange directly as `#[repr(C)]` C structs; the committed
//!   `_desc.c` descriptors are regenerated from these `.idl` with idlc (see
//!   `tools/regen-descriptors.sh`).
//!
//! POD types additionally get `#[repr(C)]` and a `DdsPod` impl carrying the C
//! topic-descriptor symbol name, so the backend can pass `&T` straight to
//! `dds_write` / receive into `T` via `dds_take` with no conversion layer.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

/// One parsed message field.
struct Field {
    name: String,
    /// Rust scalar/element type, e.g. `u8`, `f32`, `String`, `MotorCmd`.
    elem: String,
    kind: FieldKind,
}

#[derive(Clone, Copy)]
enum FieldKind {
    Scalar,
    FixedArray(usize),
    Sequence,
}

/// A parsed message type.
struct Msg {
    pkg: String,
    name: String,
    fields: Vec<Field>,
}

const PRIMITIVES: &[&str] = &[
    "bool", "i8", "u8", "i16", "u16", "i32", "u32", "i64", "u64", "f32", "f64",
];

fn main() {
    let pkgs = ["unitree_api", "unitree_go", "unitree_hg"];
    let manifest_dir = PathBuf::from(env_var("CARGO_MANIFEST_DIR"));
    let msgs_dir = manifest_dir.join("msgs");
    let out_dir = PathBuf::from(env_var("OUT_DIR"));
    println!("cargo:rerun-if-changed=msgs");

    // --- parse every .msg into Msg, preserving file (sorted) order ---
    let mut msgs: Vec<Msg> = Vec::new();
    for pkg in pkgs {
        let dir = msgs_dir.join(pkg);
        let mut files: Vec<PathBuf> = fs::read_dir(&dir)
            .unwrap_or_else(|e| panic!("read_dir {}: {e}", dir.display()))
            .filter_map(Result::ok)
            .map(|e| e.path())
            .filter(|p| p.extension().is_some_and(|x| x == "msg"))
            .collect();
        files.sort();
        for file in &files {
            println!("cargo:rerun-if-changed={}", file.display());
            let name = file.file_stem().unwrap().to_str().unwrap().to_string();
            let src = fs::read_to_string(file)
                .unwrap_or_else(|e| panic!("read {}: {e}", file.display()));
            msgs.push(Msg {
                pkg: pkg.to_string(),
                name,
                fields: parse_msg(&src),
            });
        }
    }

    // --- compute the POD set (fixed point over message references) ---
    let pod = compute_pod(&msgs);

    // --- emit generated.rs ---
    let mut out = String::new();
    out.push_str("// @generated by build.rs from msgs/*.msg — do not edit.\n\n");
    for pkg in pkgs {
        writeln!(out, "pub mod {pkg} {{").unwrap();
        out.push_str(
            "    #![allow(clippy::all)]\n\
             \x20   use crate::cdr::{CdrDeserialize, CdrDeserializer, CdrError, CdrSerialize, CdrSerializer};\n\
             \x20   use crate::{DdsType, DdsPod};\n\n",
        );
        for m in msgs.iter().filter(|m| m.pkg == pkg) {
            let is_pod = pod.contains(&key(&m.pkg, &m.name));
            emit_struct(&mut out, m, is_pod);
        }
        writeln!(out, "}}\n").unwrap();
    }
    fs::write(out_dir.join("generated.rs"), &out)
        .unwrap_or_else(|e| panic!("write generated.rs: {e}"));

    // --- emit one .idl per package for the POD subset ---
    let idl_dir = out_dir.join("idl");
    fs::create_dir_all(&idl_dir).unwrap();
    for pkg in pkgs {
        let pod_msgs: Vec<&Msg> = msgs
            .iter()
            .filter(|m| m.pkg == pkg && pod.contains(&key(&m.pkg, &m.name)))
            .collect();
        if pod_msgs.is_empty() {
            continue;
        }
        let idl = emit_idl(pkg, &pod_msgs);
        fs::write(idl_dir.join(format!("{pkg}.idl")), idl)
            .unwrap_or_else(|e| panic!("write {pkg}.idl: {e}"));
    }
}

fn parse_msg(src: &str) -> Vec<Field> {
    let mut fields = Vec::new();
    for raw in src.lines() {
        let line = match raw.split_once('#') {
            Some((before, _)) => before,
            None => raw,
        }
        .trim();
        if line.is_empty() {
            continue;
        }
        let mut it = line.split_whitespace();
        let type_tok = it.next().expect("type token");
        let name = it
            .next()
            .unwrap_or_else(|| panic!("missing field name in line: {line:?}"));
        assert!(!name.contains('='), "constants not supported: {line:?}");
        let (base, kind) = split_array(type_tok);
        fields.push(Field {
            name: sanitize_ident(name),
            elem: map_type(base),
            kind,
        });
    }
    fields
}

/// Split a type token like `uint8[40]` / `float32[]` / `int32` into
/// (base type, array kind).
fn split_array(tok: &str) -> (&str, FieldKind) {
    if let Some(open) = tok.find('[') {
        let base = &tok[..open];
        let inside = &tok[open + 1..tok.len() - 1];
        if inside.is_empty() {
            (base, FieldKind::Sequence)
        } else {
            (base, FieldKind::FixedArray(inside.parse().expect("array length")))
        }
    } else {
        (tok, FieldKind::Scalar)
    }
}

/// Map a ROS `.msg` primitive to a Rust type; otherwise treat it as a
/// same-package message reference (used verbatim).
fn map_type(t: &str) -> String {
    match t {
        "bool" => "bool",
        "int8" | "byte" => "i8",
        "uint8" | "char" => "u8",
        "int16" => "i16",
        "uint16" => "u16",
        "int32" => "i32",
        "uint32" => "u32",
        "int64" => "i64",
        "uint64" => "u64",
        "float32" => "f32",
        "float64" => "f64",
        "string" => "String",
        other => other,
    }
    .to_string()
}

/// A type is POD iff every field is a scalar/fixed-array of a primitive
/// (excluding `string`) or of another POD type. Computed as a fixed point.
fn compute_pod(msgs: &[Msg]) -> BTreeSet<String> {
    let mut pod: BTreeSet<String> = BTreeSet::new();
    loop {
        let mut changed = false;
        for m in msgs {
            let k = key(&m.pkg, &m.name);
            if pod.contains(&k) {
                continue;
            }
            if m.fields.iter().all(|f| field_is_pod(&m.pkg, f, &pod)) {
                pod.insert(k);
                changed = true;
            }
        }
        if !changed {
            break;
        }
    }
    pod
}

fn field_is_pod(pkg: &str, f: &Field, pod: &BTreeSet<String>) -> bool {
    match f.kind {
        FieldKind::Sequence => false,
        FieldKind::Scalar | FieldKind::FixedArray(_) => {
            if f.elem == "String" {
                false
            } else if PRIMITIVES.contains(&f.elem.as_str()) {
                true
            } else {
                pod.contains(&key(pkg, &f.elem))
            }
        }
    }
}

fn field_type(f: &Field) -> String {
    match f.kind {
        FieldKind::Scalar => f.elem.clone(),
        FieldKind::FixedArray(n) => format!("[{}; {}]", f.elem, n),
        FieldKind::Sequence => format!("Vec<{}>", f.elem),
    }
}

fn emit_struct(out: &mut String, m: &Msg, is_pod: bool) {
    let name = &m.name;
    let fields = &m.fields;
    if is_pod {
        writeln!(out, "    #[derive(Debug, Clone, Copy, PartialEq)]").unwrap();
        writeln!(out, "    #[repr(C)]").unwrap();
    } else {
        writeln!(out, "    #[derive(Debug, Clone, PartialEq)]").unwrap();
    }
    writeln!(out, "    pub struct {name} {{").unwrap();
    for f in fields {
        writeln!(out, "        pub {}: {},", f.name, field_type(f)).unwrap();
    }
    writeln!(out, "    }}\n").unwrap();

    // Default (manual: arrays > 32 have no derive)
    writeln!(out, "    impl Default for {name} {{").unwrap();
    writeln!(out, "        fn default() -> Self {{").unwrap();
    writeln!(out, "            Self {{").unwrap();
    for f in fields {
        let val = match f.kind {
            FieldKind::FixedArray(_) => {
                "::core::array::from_fn(|_| ::core::default::Default::default())".to_string()
            }
            _ => "::core::default::Default::default()".to_string(),
        };
        writeln!(out, "                {}: {},", f.name, val).unwrap();
    }
    writeln!(out, "            }}").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}\n").unwrap();

    // CdrSerialize
    writeln!(out, "    impl CdrSerialize for {name} {{").unwrap();
    writeln!(out, "        fn serialize(&self, s: &mut CdrSerializer) {{").unwrap();
    if fields.is_empty() {
        writeln!(out, "            let _ = s;").unwrap();
    }
    for f in fields {
        writeln!(out, "            self.{}.serialize(s);", f.name).unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}\n").unwrap();

    // CdrDeserialize
    writeln!(out, "    impl CdrDeserialize for {name} {{").unwrap();
    writeln!(
        out,
        "        fn deserialize(d: &mut CdrDeserializer<'_>) -> Result<Self, CdrError> {{"
    )
    .unwrap();
    if fields.is_empty() {
        writeln!(out, "            let _ = d;").unwrap();
    }
    writeln!(out, "            Ok(Self {{").unwrap();
    for f in fields {
        writeln!(
            out,
            "                {}: CdrDeserialize::deserialize(d)?,",
            f.name
        )
        .unwrap();
    }
    writeln!(out, "            }})").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}\n").unwrap();

    // DdsType
    writeln!(out, "    impl DdsType for {name} {{").unwrap();
    writeln!(
        out,
        "        const TYPE_NAME: &'static str = \"{}::msg::dds_::{name}_\";",
        m.pkg
    )
    .unwrap();
    writeln!(out, "        const IS_KEYLESS: bool = true;").unwrap();
    writeln!(out, "    }}\n").unwrap();

    // DdsPod (only for POD types): carries the idlc descriptor symbol name.
    if is_pod {
        let desc = format!("{}_msg_dds__{name}__desc", m.pkg);
        writeln!(out, "    impl DdsPod for {name} {{").unwrap();
        writeln!(out, "        const DESCRIPTOR_SYMBOL: &'static str = \"{desc}\";").unwrap();
        writeln!(out, "    }}\n").unwrap();
    }
}

/// Emit one `.idl` for a package's POD types, referenced types first.
fn emit_idl(pkg: &str, msgs: &[&Msg]) -> String {
    let ordered = topo_order(pkg, msgs);
    let mut s = String::new();
    writeln!(s, "// @generated by build.rs from msgs/{pkg}/*.msg — do not edit.").unwrap();
    writeln!(s, "module {pkg} {{").unwrap();
    writeln!(s, "module msg {{").unwrap();
    writeln!(s, "module dds_ {{").unwrap();
    for m in ordered {
        writeln!(s, "  struct {}_ {{", m.name).unwrap();
        for f in &m.fields {
            let ty = idl_type(&f.elem);
            // IDL has its own grammar; emit the bare field name (strip the
            // Rust raw-identifier prefix added for keywords like `fn`).
            let fname = f.name.strip_prefix("r#").unwrap_or(&f.name);
            match f.kind {
                FieldKind::FixedArray(n) => writeln!(s, "    {ty} {fname}[{n}];").unwrap(),
                _ => writeln!(s, "    {ty} {fname};").unwrap(),
            }
        }
        writeln!(s, "  }};").unwrap();
    }
    writeln!(s, "}};").unwrap();
    writeln!(s, "}};").unwrap();
    writeln!(s, "}};").unwrap();
    s
}

/// Topologically order POD messages so referenced types precede their users.
fn topo_order<'a>(pkg: &str, msgs: &[&'a Msg]) -> Vec<&'a Msg> {
    let names: BTreeSet<String> = msgs.iter().map(|m| m.name.clone()).collect();
    let mut done: BTreeSet<String> = BTreeSet::new();
    let mut out: Vec<&Msg> = Vec::new();
    // simple DFS; the reference graph is a small DAG
    fn visit<'a>(
        m: &'a Msg,
        all: &[&'a Msg],
        names: &BTreeSet<String>,
        done: &mut BTreeSet<String>,
        out: &mut Vec<&'a Msg>,
    ) {
        if done.contains(&m.name) {
            return;
        }
        for f in &m.fields {
            if names.contains(&f.elem) && f.elem != m.name {
                if let Some(dep) = all.iter().find(|x| x.name == f.elem) {
                    visit(dep, all, names, done, out);
                }
            }
        }
        done.insert(m.name.clone());
        out.push(m);
    }
    let _ = pkg;
    for m in msgs {
        visit(m, msgs, &names, &mut done, &mut out);
    }
    out
}

/// Map a Rust element type back to an IDL type. Message refs gain the `_`
/// suffix used for IDL struct names.
fn idl_type(elem: &str) -> String {
    match elem {
        "bool" => "boolean".to_string(),
        "i8" => "int8".to_string(),
        "u8" => "uint8".to_string(),
        "i16" => "int16".to_string(),
        "u16" => "uint16".to_string(),
        "i32" => "int32".to_string(),
        "u32" => "uint32".to_string(),
        "i64" => "int64".to_string(),
        "u64" => "uint64".to_string(),
        "f32" => "float".to_string(),
        "f64" => "double".to_string(),
        other => format!("{other}_"), // message reference
    }
}

fn key(pkg: &str, name: &str) -> String {
    format!("{pkg}::{name}")
}

fn sanitize_ident(name: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "as", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern", "false",
        "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub",
        "ref", "return", "self", "static", "struct", "super", "trait", "true", "type", "unsafe",
        "use", "where", "while", "async", "await",
    ];
    if KEYWORDS.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

fn env_var(k: &str) -> String {
    std::env::var(k).unwrap_or_else(|_| panic!("missing env var {k}"))
}
