//! Build script: parse the `.msg` snapshots under `msgs/` and generate Rust
//! structs with XCDR2 (de)serialization into `$OUT_DIR/generated.rs`.

use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

/// One parsed message field.
struct Field {
    name: String,
    /// Rust scalar/element type, e.g. `u8`, `f32`, `String`, `MotorCmd`.
    elem: String,
    kind: FieldKind,
}

enum FieldKind {
    Scalar,
    FixedArray(usize),
    Sequence,
}

fn main() {
    let pkgs = ["unitree_api", "unitree_go", "unitree_hg"];
    let msgs_dir = PathBuf::from(env_var("CARGO_MANIFEST_DIR")).join("msgs");
    println!("cargo:rerun-if-changed=msgs");

    let mut out = String::new();
    out.push_str("// @generated by build.rs from msgs/*.msg — do not edit.\n\n");

    for pkg in pkgs {
        let dir = msgs_dir.join(pkg);
        let mut files: Vec<PathBuf> = fs::read_dir(&dir)
            .unwrap_or_else(|e| panic!("read_dir {}: {e}", dir.display()))
            .filter_map(Result::ok)
            .map(|e| e.path())
            .filter(|p| p.extension().is_some_and(|x| x == "msg"))
            .collect();
        files.sort();

        writeln!(out, "pub mod {pkg} {{").unwrap();
        out.push_str(
            "    #![allow(clippy::all)]\n\
             \x20   use crate::cdr::{CdrDeserialize, CdrDeserializer, CdrError, CdrSerialize, CdrSerializer};\n\
             \x20   use crate::DdsType;\n\n",
        );

        for file in &files {
            let name = file.file_stem().unwrap().to_str().unwrap().to_string();
            let src = fs::read_to_string(file)
                .unwrap_or_else(|e| panic!("read {}: {e}", file.display()));
            let fields = parse_msg(&src);
            emit_struct(&mut out, pkg, &name, &fields);
            println!("cargo:rerun-if-changed={}", file.display());
        }

        writeln!(out, "}}\n").unwrap();
    }

    let out_path = PathBuf::from(env_var("OUT_DIR")).join("generated.rs");
    fs::write(&out_path, out).unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));
}

fn parse_msg(src: &str) -> Vec<Field> {
    let mut fields = Vec::new();
    for raw in src.lines() {
        // strip end-of-line comments
        let line = match raw.split_once('#') {
            Some((before, _)) => before,
            None => raw,
        }
        .trim();
        if line.is_empty() {
            continue;
        }
        let mut it = line.split_whitespace();
        let type_tok = it.next().expect("type token");
        let name = it.next().unwrap_or_else(|| panic!("missing field name in line: {line:?}"));
        // constants (`TYPE NAME=VALUE`) are not used by Unitree msgs
        assert!(!name.contains('='), "constants not supported: {line:?}");

        let (base, kind) = split_array(type_tok);
        let elem = map_type(base);
        fields.push(Field {
            name: sanitize_ident(name),
            elem,
            kind,
        });
    }
    fields
}

/// Split a type token like `uint8[40]` / `float32[]` / `int32` into
/// (base type, array kind).
fn split_array(tok: &str) -> (&str, FieldKind) {
    if let Some(open) = tok.find('[') {
        let base = &tok[..open];
        let inside = &tok[open + 1..tok.len() - 1];
        if inside.is_empty() {
            (base, FieldKind::Sequence)
        } else {
            let n: usize = inside.parse().expect("array length");
            (base, FieldKind::FixedArray(n))
        }
    } else {
        (tok, FieldKind::Scalar)
    }
}

/// Map a ROS `.msg` primitive to a Rust type; otherwise treat it as a
/// same-package message reference (used verbatim).
fn map_type(t: &str) -> String {
    match t {
        "bool" => "bool",
        "int8" | "byte" => "i8",
        "uint8" | "char" => "u8",
        "int16" => "i16",
        "uint16" => "u16",
        "int32" => "i32",
        "uint32" => "u32",
        "int64" => "i64",
        "uint64" => "u64",
        "float32" => "f32",
        "float64" => "f64",
        "string" => "String",
        other => other,
    }
    .to_string()
}

/// Rust type for a field (element type wrapped by its array kind).
fn field_type(f: &Field) -> String {
    match f.kind {
        FieldKind::Scalar => f.elem.clone(),
        FieldKind::FixedArray(n) => format!("[{}; {}]", f.elem, n),
        FieldKind::Sequence => format!("Vec<{}>", f.elem),
    }
}

fn emit_struct(out: &mut String, pkg: &str, name: &str, fields: &[Field]) {
    // struct definition (Default is impl'd manually: arrays > 32 have no derive)
    writeln!(out, "    #[derive(Debug, Clone, PartialEq)]").unwrap();
    writeln!(out, "    pub struct {name} {{").unwrap();
    for f in fields {
        writeln!(out, "        pub {}: {},", f.name, field_type(f)).unwrap();
    }
    writeln!(out, "    }}\n").unwrap();

    // Default
    writeln!(out, "    impl Default for {name} {{").unwrap();
    writeln!(out, "        fn default() -> Self {{").unwrap();
    writeln!(out, "            Self {{").unwrap();
    for f in fields {
        let val = match f.kind {
            FieldKind::FixedArray(_) => {
                "::core::array::from_fn(|_| ::core::default::Default::default())".to_string()
            }
            _ => "::core::default::Default::default()".to_string(),
        };
        writeln!(out, "                {}: {},", f.name, val).unwrap();
    }
    writeln!(out, "            }}").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}\n").unwrap();

    // CdrSerialize
    writeln!(out, "    impl CdrSerialize for {name} {{").unwrap();
    writeln!(out, "        fn serialize(&self, s: &mut CdrSerializer) {{").unwrap();
    if fields.is_empty() {
        writeln!(out, "            let _ = s;").unwrap();
    }
    for f in fields {
        writeln!(out, "            self.{}.serialize(s);", f.name).unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}\n").unwrap();

    // CdrDeserialize
    writeln!(out, "    impl CdrDeserialize for {name} {{").unwrap();
    writeln!(
        out,
        "        fn deserialize(d: &mut CdrDeserializer<'_>) -> Result<Self, CdrError> {{"
    )
    .unwrap();
    if fields.is_empty() {
        writeln!(out, "            let _ = d;").unwrap();
    }
    writeln!(out, "            Ok(Self {{").unwrap();
    for f in fields {
        writeln!(
            out,
            "                {}: CdrDeserialize::deserialize(d)?,",
            f.name
        )
        .unwrap();
    }
    writeln!(out, "            }})").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}\n").unwrap();

    // DdsType
    writeln!(out, "    impl DdsType for {name} {{").unwrap();
    writeln!(
        out,
        "        const TYPE_NAME: &'static str = \"{pkg}::msg::dds_::{name}_\";"
    )
    .unwrap();
    writeln!(out, "        const IS_KEYLESS: bool = true;").unwrap();
    writeln!(out, "    }}\n").unwrap();
}

/// Wrap Rust keywords as raw identifiers.
fn sanitize_ident(name: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "as", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern", "false",
        "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub",
        "ref", "return", "self", "static", "struct", "super", "trait", "true", "type", "unsafe",
        "use", "where", "while", "async", "await",
    ];
    if KEYWORDS.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

fn env_var(k: &str) -> String {
    std::env::var(k).unwrap_or_else(|_| panic!("missing env var {k}"))
}
