/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: unitree_hg.h
  Source: /home/takara/work/keel/unitree-sdk-rs/crates/unitree-dds/csrc/unitree_hg.idl
  Cyclone DDS: V0.10.2

*****************************************************************/
#ifndef DDSC_UNITREE_HG_H
#define DDSC_UNITREE_HG_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct unitree_hg_msg_dds__BmsCmd_
{
  uint8_t cmd;
  uint8_t reserve[40];
} unitree_hg_msg_dds__BmsCmd_;

extern const dds_topic_descriptor_t unitree_hg_msg_dds__BmsCmd__desc;

#define unitree_hg_msg_dds__BmsCmd___alloc() \
((unitree_hg_msg_dds__BmsCmd_*) dds_alloc (sizeof (unitree_hg_msg_dds__BmsCmd_)));

#define unitree_hg_msg_dds__BmsCmd__free(d,o) \
dds_sample_free ((d), &unitree_hg_msg_dds__BmsCmd__desc, (o))

typedef struct unitree_hg_msg_dds__BmsState_
{
  uint8_t version_high;
  uint8_t version_low;
  uint8_t fn;
  uint16_t cell_vol[40];
  uint32_t bmsvoltage[3];
  int32_t current;
  uint8_t soc;
  uint8_t soh;
  int16_t temperature[12];
  uint16_t cycle;
  uint16_t manufacturer_date;
  uint32_t bmsstate[5];
  uint32_t reserve[3];
} unitree_hg_msg_dds__BmsState_;

extern const dds_topic_descriptor_t unitree_hg_msg_dds__BmsState__desc;

#define unitree_hg_msg_dds__BmsState___alloc() \
((unitree_hg_msg_dds__BmsState_*) dds_alloc (sizeof (unitree_hg_msg_dds__BmsState_)));

#define unitree_hg_msg_dds__BmsState__free(d,o) \
dds_sample_free ((d), &unitree_hg_msg_dds__BmsState__desc, (o))

typedef struct unitree_hg_msg_dds__IMUState_
{
  float quaternion[4];
  float gyroscope[3];
  float accelerometer[3];
  float rpy[3];
  int16_t temperature;
} unitree_hg_msg_dds__IMUState_;

extern const dds_topic_descriptor_t unitree_hg_msg_dds__IMUState__desc;

#define unitree_hg_msg_dds__IMUState___alloc() \
((unitree_hg_msg_dds__IMUState_*) dds_alloc (sizeof (unitree_hg_msg_dds__IMUState_)));

#define unitree_hg_msg_dds__IMUState__free(d,o) \
dds_sample_free ((d), &unitree_hg_msg_dds__IMUState__desc, (o))

typedef struct unitree_hg_msg_dds__MotorCmd_
{
  uint8_t mode;
  float q;
  float dq;
  float tau;
  float kp;
  float kd;
  uint32_t reserve;
} unitree_hg_msg_dds__MotorCmd_;

extern const dds_topic_descriptor_t unitree_hg_msg_dds__MotorCmd__desc;

#define unitree_hg_msg_dds__MotorCmd___alloc() \
((unitree_hg_msg_dds__MotorCmd_*) dds_alloc (sizeof (unitree_hg_msg_dds__MotorCmd_)));

#define unitree_hg_msg_dds__MotorCmd__free(d,o) \
dds_sample_free ((d), &unitree_hg_msg_dds__MotorCmd__desc, (o))

typedef struct unitree_hg_msg_dds__LowCmd_
{
  uint8_t mode_pr;
  uint8_t mode_machine;
  struct unitree_hg_msg_dds__MotorCmd_ motor_cmd[35];
  uint32_t reserve[4];
  uint32_t crc;
} unitree_hg_msg_dds__LowCmd_;

extern const dds_topic_descriptor_t unitree_hg_msg_dds__LowCmd__desc;

#define unitree_hg_msg_dds__LowCmd___alloc() \
((unitree_hg_msg_dds__LowCmd_*) dds_alloc (sizeof (unitree_hg_msg_dds__LowCmd_)));

#define unitree_hg_msg_dds__LowCmd__free(d,o) \
dds_sample_free ((d), &unitree_hg_msg_dds__LowCmd__desc, (o))

typedef struct unitree_hg_msg_dds__MotorState_
{
  uint8_t mode;
  float q;
  float dq;
  float ddq;
  float tau_est;
  int16_t temperature[2];
  float vol;
  uint32_t sensor[2];
  uint32_t motorstate;
  uint32_t reserve[4];
} unitree_hg_msg_dds__MotorState_;

extern const dds_topic_descriptor_t unitree_hg_msg_dds__MotorState__desc;

#define unitree_hg_msg_dds__MotorState___alloc() \
((unitree_hg_msg_dds__MotorState_*) dds_alloc (sizeof (unitree_hg_msg_dds__MotorState_)));

#define unitree_hg_msg_dds__MotorState__free(d,o) \
dds_sample_free ((d), &unitree_hg_msg_dds__MotorState__desc, (o))

typedef struct unitree_hg_msg_dds__LowState_
{
  uint32_t version[2];
  uint8_t mode_pr;
  uint8_t mode_machine;
  uint32_t tick;
  struct unitree_hg_msg_dds__IMUState_ imu_state;
  struct unitree_hg_msg_dds__MotorState_ motor_state[35];
  uint8_t wireless_remote[40];
  uint32_t reserve[4];
  uint32_t crc;
} unitree_hg_msg_dds__LowState_;

extern const dds_topic_descriptor_t unitree_hg_msg_dds__LowState__desc;

#define unitree_hg_msg_dds__LowState___alloc() \
((unitree_hg_msg_dds__LowState_*) dds_alloc (sizeof (unitree_hg_msg_dds__LowState_)));

#define unitree_hg_msg_dds__LowState__free(d,o) \
dds_sample_free ((d), &unitree_hg_msg_dds__LowState__desc, (o))

typedef struct unitree_hg_msg_dds__MainBoardState_
{
  uint16_t fan_state[6];
  int16_t temperature[6];
  float value[6];
  uint32_t state[6];
} unitree_hg_msg_dds__MainBoardState_;

extern const dds_topic_descriptor_t unitree_hg_msg_dds__MainBoardState__desc;

#define unitree_hg_msg_dds__MainBoardState___alloc() \
((unitree_hg_msg_dds__MainBoardState_*) dds_alloc (sizeof (unitree_hg_msg_dds__MainBoardState_)));

#define unitree_hg_msg_dds__MainBoardState__free(d,o) \
dds_sample_free ((d), &unitree_hg_msg_dds__MainBoardState__desc, (o))

typedef struct unitree_hg_msg_dds__PressSensorState_
{
  float pressure[12];
  float temperature[12];
  uint32_t lost;
  uint32_t reserve;
} unitree_hg_msg_dds__PressSensorState_;

extern const dds_topic_descriptor_t unitree_hg_msg_dds__PressSensorState__desc;

#define unitree_hg_msg_dds__PressSensorState___alloc() \
((unitree_hg_msg_dds__PressSensorState_*) dds_alloc (sizeof (unitree_hg_msg_dds__PressSensorState_)));

#define unitree_hg_msg_dds__PressSensorState__free(d,o) \
dds_sample_free ((d), &unitree_hg_msg_dds__PressSensorState__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_UNITREE_HG_H */
