/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: unitree_api.h
  Source: /home/takara/work/keel/unitree-sdk-rs/crates/unitree-dds/csrc/unitree_api.idl
  Cyclone DDS: V0.10.2

*****************************************************************/
#ifndef DDSC_UNITREE_API_H
#define DDSC_UNITREE_API_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct unitree_api_msg_dds__RequestIdentity_
{
  int64_t id;
  int64_t api_id;
} unitree_api_msg_dds__RequestIdentity_;

extern const dds_topic_descriptor_t unitree_api_msg_dds__RequestIdentity__desc;

#define unitree_api_msg_dds__RequestIdentity___alloc() \
((unitree_api_msg_dds__RequestIdentity_*) dds_alloc (sizeof (unitree_api_msg_dds__RequestIdentity_)));

#define unitree_api_msg_dds__RequestIdentity__free(d,o) \
dds_sample_free ((d), &unitree_api_msg_dds__RequestIdentity__desc, (o))

typedef struct unitree_api_msg_dds__RequestLease_
{
  int64_t id;
} unitree_api_msg_dds__RequestLease_;

extern const dds_topic_descriptor_t unitree_api_msg_dds__RequestLease__desc;

#define unitree_api_msg_dds__RequestLease___alloc() \
((unitree_api_msg_dds__RequestLease_*) dds_alloc (sizeof (unitree_api_msg_dds__RequestLease_)));

#define unitree_api_msg_dds__RequestLease__free(d,o) \
dds_sample_free ((d), &unitree_api_msg_dds__RequestLease__desc, (o))

typedef struct unitree_api_msg_dds__RequestPolicy_
{
  int32_t priority;
  bool noreply;
} unitree_api_msg_dds__RequestPolicy_;

extern const dds_topic_descriptor_t unitree_api_msg_dds__RequestPolicy__desc;

#define unitree_api_msg_dds__RequestPolicy___alloc() \
((unitree_api_msg_dds__RequestPolicy_*) dds_alloc (sizeof (unitree_api_msg_dds__RequestPolicy_)));

#define unitree_api_msg_dds__RequestPolicy__free(d,o) \
dds_sample_free ((d), &unitree_api_msg_dds__RequestPolicy__desc, (o))

typedef struct unitree_api_msg_dds__RequestHeader_
{
  struct unitree_api_msg_dds__RequestIdentity_ identity;
  struct unitree_api_msg_dds__RequestLease_ lease;
  struct unitree_api_msg_dds__RequestPolicy_ policy;
} unitree_api_msg_dds__RequestHeader_;

extern const dds_topic_descriptor_t unitree_api_msg_dds__RequestHeader__desc;

#define unitree_api_msg_dds__RequestHeader___alloc() \
((unitree_api_msg_dds__RequestHeader_*) dds_alloc (sizeof (unitree_api_msg_dds__RequestHeader_)));

#define unitree_api_msg_dds__RequestHeader__free(d,o) \
dds_sample_free ((d), &unitree_api_msg_dds__RequestHeader__desc, (o))

typedef struct unitree_api_msg_dds__ResponseStatus_
{
  int32_t code;
} unitree_api_msg_dds__ResponseStatus_;

extern const dds_topic_descriptor_t unitree_api_msg_dds__ResponseStatus__desc;

#define unitree_api_msg_dds__ResponseStatus___alloc() \
((unitree_api_msg_dds__ResponseStatus_*) dds_alloc (sizeof (unitree_api_msg_dds__ResponseStatus_)));

#define unitree_api_msg_dds__ResponseStatus__free(d,o) \
dds_sample_free ((d), &unitree_api_msg_dds__ResponseStatus__desc, (o))

typedef struct unitree_api_msg_dds__ResponseHeader_
{
  struct unitree_api_msg_dds__RequestIdentity_ identity;
  struct unitree_api_msg_dds__ResponseStatus_ status;
} unitree_api_msg_dds__ResponseHeader_;

extern const dds_topic_descriptor_t unitree_api_msg_dds__ResponseHeader__desc;

#define unitree_api_msg_dds__ResponseHeader___alloc() \
((unitree_api_msg_dds__ResponseHeader_*) dds_alloc (sizeof (unitree_api_msg_dds__ResponseHeader_)));

#define unitree_api_msg_dds__ResponseHeader__free(d,o) \
dds_sample_free ((d), &unitree_api_msg_dds__ResponseHeader__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_UNITREE_API_H */
