/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: unitree_go.h
  Source: /home/takara/work/keel/unitree-sdk-rs/crates/unitree-dds/csrc/unitree_go.idl
  Cyclone DDS: V0.10.2

*****************************************************************/
#ifndef DDSC_UNITREE_GO_H
#define DDSC_UNITREE_GO_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct unitree_go_msg_dds__BmsCmd_
{
  uint8_t off;
  uint8_t reserve[3];
} unitree_go_msg_dds__BmsCmd_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__BmsCmd__desc;

#define unitree_go_msg_dds__BmsCmd___alloc() \
((unitree_go_msg_dds__BmsCmd_*) dds_alloc (sizeof (unitree_go_msg_dds__BmsCmd_)));

#define unitree_go_msg_dds__BmsCmd__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__BmsCmd__desc, (o))

typedef struct unitree_go_msg_dds__BmsState_
{
  uint8_t version_high;
  uint8_t version_low;
  uint8_t status;
  uint8_t soc;
  int32_t current;
  uint16_t cycle;
  int8_t bq_ntc[2];
  int8_t mcu_ntc[2];
  uint16_t cell_vol[15];
} unitree_go_msg_dds__BmsState_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__BmsState__desc;

#define unitree_go_msg_dds__BmsState___alloc() \
((unitree_go_msg_dds__BmsState_*) dds_alloc (sizeof (unitree_go_msg_dds__BmsState_)));

#define unitree_go_msg_dds__BmsState__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__BmsState__desc, (o))

typedef struct unitree_go_msg_dds__Error_
{
  uint32_t source;
  uint32_t state;
} unitree_go_msg_dds__Error_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__Error__desc;

#define unitree_go_msg_dds__Error___alloc() \
((unitree_go_msg_dds__Error_*) dds_alloc (sizeof (unitree_go_msg_dds__Error_)));

#define unitree_go_msg_dds__Error__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__Error__desc, (o))

typedef struct unitree_go_msg_dds__IMUState_
{
  float quaternion[4];
  float gyroscope[3];
  float accelerometer[3];
  float rpy[3];
  int8_t temperature;
} unitree_go_msg_dds__IMUState_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__IMUState__desc;

#define unitree_go_msg_dds__IMUState___alloc() \
((unitree_go_msg_dds__IMUState_*) dds_alloc (sizeof (unitree_go_msg_dds__IMUState_)));

#define unitree_go_msg_dds__IMUState__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__IMUState__desc, (o))

typedef struct unitree_go_msg_dds__InterfaceConfig_
{
  uint8_t mode;
  uint8_t value;
  uint8_t reserve[2];
} unitree_go_msg_dds__InterfaceConfig_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__InterfaceConfig__desc;

#define unitree_go_msg_dds__InterfaceConfig___alloc() \
((unitree_go_msg_dds__InterfaceConfig_*) dds_alloc (sizeof (unitree_go_msg_dds__InterfaceConfig_)));

#define unitree_go_msg_dds__InterfaceConfig__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__InterfaceConfig__desc, (o))

typedef struct unitree_go_msg_dds__MotorCmd_
{
  uint8_t mode;
  float q;
  float dq;
  float tau;
  float kp;
  float kd;
  uint32_t reserve[3];
} unitree_go_msg_dds__MotorCmd_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__MotorCmd__desc;

#define unitree_go_msg_dds__MotorCmd___alloc() \
((unitree_go_msg_dds__MotorCmd_*) dds_alloc (sizeof (unitree_go_msg_dds__MotorCmd_)));

#define unitree_go_msg_dds__MotorCmd__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__MotorCmd__desc, (o))

typedef struct unitree_go_msg_dds__LowCmd_
{
  uint8_t head[2];
  uint8_t level_flag;
  uint8_t frame_reserve;
  uint32_t sn[2];
  uint32_t version[2];
  uint16_t bandwidth;
  struct unitree_go_msg_dds__MotorCmd_ motor_cmd[20];
  struct unitree_go_msg_dds__BmsCmd_ bms_cmd;
  uint8_t wireless_remote[40];
  uint8_t led[12];
  uint8_t fan[2];
  uint8_t gpio;
  uint32_t reserve;
  uint32_t crc;
} unitree_go_msg_dds__LowCmd_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__LowCmd__desc;

#define unitree_go_msg_dds__LowCmd___alloc() \
((unitree_go_msg_dds__LowCmd_*) dds_alloc (sizeof (unitree_go_msg_dds__LowCmd_)));

#define unitree_go_msg_dds__LowCmd__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__LowCmd__desc, (o))

typedef struct unitree_go_msg_dds__MotorState_
{
  uint8_t mode;
  float q;
  float dq;
  float ddq;
  float tau_est;
  float q_raw;
  float dq_raw;
  float ddq_raw;
  int8_t temperature;
  uint32_t lost;
  uint32_t reserve[2];
} unitree_go_msg_dds__MotorState_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__MotorState__desc;

#define unitree_go_msg_dds__MotorState___alloc() \
((unitree_go_msg_dds__MotorState_*) dds_alloc (sizeof (unitree_go_msg_dds__MotorState_)));

#define unitree_go_msg_dds__MotorState__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__MotorState__desc, (o))

typedef struct unitree_go_msg_dds__LowState_
{
  uint8_t head[2];
  uint8_t level_flag;
  uint8_t frame_reserve;
  uint32_t sn[2];
  uint32_t version[2];
  uint16_t bandwidth;
  struct unitree_go_msg_dds__IMUState_ imu_state;
  struct unitree_go_msg_dds__MotorState_ motor_state[20];
  struct unitree_go_msg_dds__BmsState_ bms_state;
  int16_t foot_force[4];
  int16_t foot_force_est[4];
  uint32_t tick;
  uint8_t wireless_remote[40];
  uint8_t bit_flag;
  float adc_reel;
  int8_t temperature_ntc1;
  int8_t temperature_ntc2;
  float power_v;
  float power_a;
  uint16_t fan_frequency[4];
  uint32_t reserve;
  uint32_t crc;
} unitree_go_msg_dds__LowState_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__LowState__desc;

#define unitree_go_msg_dds__LowState___alloc() \
((unitree_go_msg_dds__LowState_*) dds_alloc (sizeof (unitree_go_msg_dds__LowState_)));

#define unitree_go_msg_dds__LowState__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__LowState__desc, (o))

typedef struct unitree_go_msg_dds__PathPoint_
{
  float t_from_start;
  float x;
  float y;
  float yaw;
  float vx;
  float vy;
  float vyaw;
} unitree_go_msg_dds__PathPoint_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__PathPoint__desc;

#define unitree_go_msg_dds__PathPoint___alloc() \
((unitree_go_msg_dds__PathPoint_*) dds_alloc (sizeof (unitree_go_msg_dds__PathPoint_)));

#define unitree_go_msg_dds__PathPoint__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__PathPoint__desc, (o))

typedef struct unitree_go_msg_dds__SportModeCmd_
{
  uint8_t mode;
  uint8_t gait_type;
  uint8_t speed_level;
  float foot_raise_height;
  float body_height;
  float position[2];
  float euler[3];
  float velocity[2];
  float yaw_speed;
  struct unitree_go_msg_dds__BmsCmd_ bms_cmd;
  struct unitree_go_msg_dds__PathPoint_ path_point[30];
} unitree_go_msg_dds__SportModeCmd_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__SportModeCmd__desc;

#define unitree_go_msg_dds__SportModeCmd___alloc() \
((unitree_go_msg_dds__SportModeCmd_*) dds_alloc (sizeof (unitree_go_msg_dds__SportModeCmd_)));

#define unitree_go_msg_dds__SportModeCmd__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__SportModeCmd__desc, (o))

typedef struct unitree_go_msg_dds__TimeSpec_
{
  int32_t sec;
  uint32_t nanosec;
} unitree_go_msg_dds__TimeSpec_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__TimeSpec__desc;

#define unitree_go_msg_dds__TimeSpec___alloc() \
((unitree_go_msg_dds__TimeSpec_*) dds_alloc (sizeof (unitree_go_msg_dds__TimeSpec_)));

#define unitree_go_msg_dds__TimeSpec__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__TimeSpec__desc, (o))

typedef struct unitree_go_msg_dds__SportModeState_
{
  struct unitree_go_msg_dds__TimeSpec_ stamp;
  uint32_t error_code;
  struct unitree_go_msg_dds__IMUState_ imu_state;
  uint8_t mode;
  float progress;
  uint8_t gait_type;
  float foot_raise_height;
  float position[3];
  float body_height;
  float velocity[3];
  float yaw_speed;
  float range_obstacle[4];
  int16_t foot_force[4];
  float foot_position_body[12];
  float foot_speed_body[12];
} unitree_go_msg_dds__SportModeState_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__SportModeState__desc;

#define unitree_go_msg_dds__SportModeState___alloc() \
((unitree_go_msg_dds__SportModeState_*) dds_alloc (sizeof (unitree_go_msg_dds__SportModeState_)));

#define unitree_go_msg_dds__SportModeState__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__SportModeState__desc, (o))

typedef struct unitree_go_msg_dds__UwbState_
{
  uint8_t version[2];
  uint8_t channel;
  uint8_t joy_mode;
  float orientation_est;
  float pitch_est;
  float distance_est;
  float yaw_est;
  float tag_roll;
  float tag_pitch;
  float tag_yaw;
  float base_roll;
  float base_pitch;
  float base_yaw;
  float joystick[2];
  uint8_t error_state;
  uint8_t buttons;
  uint8_t enabled_from_app;
} unitree_go_msg_dds__UwbState_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__UwbState__desc;

#define unitree_go_msg_dds__UwbState___alloc() \
((unitree_go_msg_dds__UwbState_*) dds_alloc (sizeof (unitree_go_msg_dds__UwbState_)));

#define unitree_go_msg_dds__UwbState__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__UwbState__desc, (o))

typedef struct unitree_go_msg_dds__UwbSwitch_
{
  uint8_t enabled;
} unitree_go_msg_dds__UwbSwitch_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__UwbSwitch__desc;

#define unitree_go_msg_dds__UwbSwitch___alloc() \
((unitree_go_msg_dds__UwbSwitch_*) dds_alloc (sizeof (unitree_go_msg_dds__UwbSwitch_)));

#define unitree_go_msg_dds__UwbSwitch__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__UwbSwitch__desc, (o))

typedef struct unitree_go_msg_dds__WirelessController_
{
  float lx;
  float ly;
  float rx;
  float ry;
  uint16_t keys;
} unitree_go_msg_dds__WirelessController_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__WirelessController__desc;

#define unitree_go_msg_dds__WirelessController___alloc() \
((unitree_go_msg_dds__WirelessController_*) dds_alloc (sizeof (unitree_go_msg_dds__WirelessController_)));

#define unitree_go_msg_dds__WirelessController__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__WirelessController__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_UNITREE_GO_H */
