/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: std_msgs.h
  Source: /home/kasai/work/dp/unitree-sdk-rs/crates/unitree-go2/csrc/std_msgs.idl
  Cyclone DDS: V0.10.2

*****************************************************************/
#ifndef DDSC_STD_MSGS_H
#define DDSC_STD_MSGS_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct std_msgs_msg_dds__String_
{
  char * data;
} std_msgs_msg_dds__String_;

extern const dds_topic_descriptor_t std_msgs_msg_dds__String__desc;

#define std_msgs_msg_dds__String___alloc() \
((std_msgs_msg_dds__String_*) dds_alloc (sizeof (std_msgs_msg_dds__String_)));

#define std_msgs_msg_dds__String__free(d,o) \
dds_sample_free ((d), &std_msgs_msg_dds__String__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_STD_MSGS_H */
