//! Cyclone DDS backend over `cyclonedds-sys` (libddsc), C-struct data path.

use std::ffi::{c_void, CString};
use std::ptr;

use cyclonedds_sys as dds;

use crate::error::{DdsError, Result};
use crate::qos::{Durability, History, ReaderQos, Reliability, WriterQos};

use super::DdsBackend;

/// `DDS_DOMAIN_DEFAULT` is a `#define`, not emitted by bindgen.
const DDS_DOMAIN_DEFAULT: dds::dds_domainid_t = 0xFFFF_FFFF;

/// `DDS_INFINITY` is a `#define` (`INT64_MAX` nanoseconds), not emitted by bindgen.
const DDS_INFINITY: dds::dds_duration_t = i64::MAX;

/// A type that the Cyclone backend can exchange: a POD message with a C topic
/// descriptor generated by idlc and linked from this crate.
///
/// # Safety
/// [`descriptor`](CycloneType::descriptor) must return a pointer to the
/// `dds_topic_descriptor_t` that idlc generated for exactly this type's
/// `#[repr(C)]` layout. The generated impls in `descriptors.rs` satisfy this.
pub unsafe trait CycloneType: unitree_msgs::DdsPod {
    /// The idlc-generated topic descriptor for this type.
    fn descriptor() -> *const dds::dds_topic_descriptor_t;
}

// Generated `extern "C"` descriptor statics + `CycloneType` impls.
include!(concat!(env!("OUT_DIR"), "/descriptors.rs"));

/// Convert a negative `dds_return_t` into an error.
fn check(code: dds::dds_return_t, op: &'static str) -> Result<()> {
    if code < 0 {
        Err(DdsError::Native { op, code })
    } else {
        Ok(())
    }
}

/// An owned participant entity; deleting it cascades to its topics/endpoints.
pub(crate) struct Participant {
    entity: dds::dds_entity_t,
}

impl Drop for Participant {
    fn drop(&mut self) {
        unsafe {
            dds::dds_delete(self.entity);
        }
    }
}

/// Cyclone DDS backend marker.
pub(crate) struct CycloneBackend;

impl DdsBackend for CycloneBackend {
    type Participant = Participant;
    type Topic = dds::dds_entity_t;
    type Writer = dds::dds_entity_t;
    type Reader = dds::dds_entity_t;

    fn create_participant(domain: u32, iface: Option<&str>) -> Result<Self::Participant> {
        // Cyclone reads the interface selection from CYCLONEDDS_URI (XML). This
        // mutates process-wide env, so callers must create participants from a
        // single thread before spawning workers (documented on Participant::new).
        if let Some(iface) = iface {
            let xml = format!(
                "<CycloneDDS><Domain><General><Interfaces>\
                 <NetworkInterface name=\"{iface}\" priority=\"default\" multicast=\"default\"/>\
                 </Interfaces></General></Domain></CycloneDDS>"
            );
            std::env::set_var("CYCLONEDDS_URI", xml);
        }
        let domain = if domain == u32::MAX {
            DDS_DOMAIN_DEFAULT
        } else {
            domain
        };
        let entity = unsafe { dds::dds_create_participant(domain, ptr::null(), ptr::null()) };
        check(entity, "dds_create_participant")?;
        Ok(Participant { entity })
    }

    fn create_topic<T: crate::Message>(
        participant: &Self::Participant,
        name: &str,
    ) -> Result<Self::Topic> {
        let cname = CString::new(name).map_err(|_| DdsError::TopicCreate {
            name: name.to_string(),
        })?;
        let topic = unsafe {
            dds::dds_create_topic(
                participant.entity,
                T::descriptor(),
                cname.as_ptr(),
                ptr::null(),
                ptr::null(),
            )
        };
        if topic < 0 {
            return Err(DdsError::TopicCreate {
                name: name.to_string(),
            });
        }
        Ok(topic)
    }

    fn create_writer(
        participant: &Self::Participant,
        topic: &Self::Topic,
        qos: &WriterQos,
    ) -> Result<Self::Writer> {
        let q = build_qos(qos.reliability, qos.history, qos.durability);
        let writer = unsafe { dds::dds_create_writer(participant.entity, *topic, q, ptr::null()) };
        unsafe { dds::dds_delete_qos(q) };
        check(writer, "dds_create_writer")?;
        Ok(writer)
    }

    fn create_reader(
        participant: &Self::Participant,
        topic: &Self::Topic,
        qos: &ReaderQos,
    ) -> Result<Self::Reader> {
        let q = build_qos(qos.reliability, qos.history, qos.durability);
        let reader = unsafe { dds::dds_create_reader(participant.entity, *topic, q, ptr::null()) };
        unsafe { dds::dds_delete_qos(q) };
        check(reader, "dds_create_reader")?;
        Ok(reader)
    }

    fn write<T: crate::Message>(writer: &Self::Writer, sample: &T) -> Result<()> {
        // `T` is `#[repr(C)]` matching the idlc C struct, so a pointer to it is
        // a valid sample pointer for dds_write.
        let rc = unsafe { dds::dds_write(*writer, (sample as *const T).cast::<c_void>()) };
        check(rc, "dds_write")
    }

    fn take<T: crate::Message>(reader: &Self::Reader) -> Result<Option<T>> {
        let mut samples: [*mut c_void; 1] = [ptr::null_mut()];
        let mut infos: [dds::dds_sample_info_t; 1] = unsafe { std::mem::zeroed() };
        let n = unsafe { dds::dds_take(*reader, samples.as_mut_ptr(), infos.as_mut_ptr(), 1, 1) };
        check(n, "dds_take")?;
        if n > 0 && infos[0].valid_data {
            // POD sample: copy it out by value (T: Copy, no owned pointers).
            let value = unsafe { ptr::read(samples[0].cast::<T>()) };
            let rc = unsafe { dds::dds_return_loan(*reader, samples.as_mut_ptr(), n) };
            check(rc, "dds_return_loan")?;
            Ok(Some(value))
        } else {
            Ok(None)
        }
    }
}

/// Build a `dds_qos_t*` from our QoS enums. Caller owns the result.
fn build_qos(rel: Reliability, hist: History, dur: Durability) -> *mut dds::dds_qos_t {
    unsafe {
        let q = dds::dds_create_qos();
        match rel {
            Reliability::BestEffort => dds::dds_qset_reliability(
                q,
                dds::dds_reliability_kind::DDS_RELIABILITY_BEST_EFFORT,
                0,
            ),
            Reliability::Reliable => dds::dds_qset_reliability(
                q,
                dds::dds_reliability_kind::DDS_RELIABILITY_RELIABLE,
                DDS_INFINITY,
            ),
        }
        match hist {
            History::KeepLast(depth) => dds::dds_qset_history(
                q,
                dds::dds_history_kind::DDS_HISTORY_KEEP_LAST,
                depth as i32,
            ),
            History::KeepAll => {
                dds::dds_qset_history(q, dds::dds_history_kind::DDS_HISTORY_KEEP_ALL, 0)
            }
        }
        match dur {
            Durability::Volatile => {
                dds::dds_qset_durability(q, dds::dds_durability_kind::DDS_DURABILITY_VOLATILE)
            }
            Durability::TransientLocal => dds::dds_qset_durability(
                q,
                dds::dds_durability_kind::DDS_DURABILITY_TRANSIENT_LOCAL,
            ),
        }
        q
    }
}
