/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: rpc.h
  Source: /tmp/rpcgen/rpc.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_RPC_H
#define DDSC_RPC_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct unitree_api_msg_dds__RequestIdentity_
{
  int64_t id;
  int64_t api_id;
} unitree_api_msg_dds__RequestIdentity_;

extern const dds_topic_descriptor_t unitree_api_msg_dds__RequestIdentity__desc;

#define unitree_api_msg_dds__RequestIdentity___alloc() \
((unitree_api_msg_dds__RequestIdentity_*) dds_alloc (sizeof (unitree_api_msg_dds__RequestIdentity_)));

#define unitree_api_msg_dds__RequestIdentity__free(d,o) \
dds_sample_free ((d), &unitree_api_msg_dds__RequestIdentity__desc, (o))

typedef struct unitree_api_msg_dds__RequestLease_
{
  int64_t id;
} unitree_api_msg_dds__RequestLease_;

extern const dds_topic_descriptor_t unitree_api_msg_dds__RequestLease__desc;

#define unitree_api_msg_dds__RequestLease___alloc() \
((unitree_api_msg_dds__RequestLease_*) dds_alloc (sizeof (unitree_api_msg_dds__RequestLease_)));

#define unitree_api_msg_dds__RequestLease__free(d,o) \
dds_sample_free ((d), &unitree_api_msg_dds__RequestLease__desc, (o))

typedef struct unitree_api_msg_dds__RequestPolicy_
{
  int32_t priority;
  bool noreply;
} unitree_api_msg_dds__RequestPolicy_;

extern const dds_topic_descriptor_t unitree_api_msg_dds__RequestPolicy__desc;

#define unitree_api_msg_dds__RequestPolicy___alloc() \
((unitree_api_msg_dds__RequestPolicy_*) dds_alloc (sizeof (unitree_api_msg_dds__RequestPolicy_)));

#define unitree_api_msg_dds__RequestPolicy__free(d,o) \
dds_sample_free ((d), &unitree_api_msg_dds__RequestPolicy__desc, (o))

typedef struct unitree_api_msg_dds__RequestHeader_
{
  struct unitree_api_msg_dds__RequestIdentity_ identity;
  struct unitree_api_msg_dds__RequestLease_ lease;
  struct unitree_api_msg_dds__RequestPolicy_ policy;
} unitree_api_msg_dds__RequestHeader_;

extern const dds_topic_descriptor_t unitree_api_msg_dds__RequestHeader__desc;

#define unitree_api_msg_dds__RequestHeader___alloc() \
((unitree_api_msg_dds__RequestHeader_*) dds_alloc (sizeof (unitree_api_msg_dds__RequestHeader_)));

#define unitree_api_msg_dds__RequestHeader__free(d,o) \
dds_sample_free ((d), &unitree_api_msg_dds__RequestHeader__desc, (o))

typedef struct unitree_api_msg_dds__ResponseStatus_
{
  int32_t code;
} unitree_api_msg_dds__ResponseStatus_;

extern const dds_topic_descriptor_t unitree_api_msg_dds__ResponseStatus__desc;

#define unitree_api_msg_dds__ResponseStatus___alloc() \
((unitree_api_msg_dds__ResponseStatus_*) dds_alloc (sizeof (unitree_api_msg_dds__ResponseStatus_)));

#define unitree_api_msg_dds__ResponseStatus__free(d,o) \
dds_sample_free ((d), &unitree_api_msg_dds__ResponseStatus__desc, (o))

typedef struct unitree_api_msg_dds__ResponseHeader_
{
  struct unitree_api_msg_dds__RequestIdentity_ identity;
  struct unitree_api_msg_dds__ResponseStatus_ status;
} unitree_api_msg_dds__ResponseHeader_;

extern const dds_topic_descriptor_t unitree_api_msg_dds__ResponseHeader__desc;

#define unitree_api_msg_dds__ResponseHeader___alloc() \
((unitree_api_msg_dds__ResponseHeader_*) dds_alloc (sizeof (unitree_api_msg_dds__ResponseHeader_)));

#define unitree_api_msg_dds__ResponseHeader__free(d,o) \
dds_sample_free ((d), &unitree_api_msg_dds__ResponseHeader__desc, (o))

#ifndef DDS_SEQUENCE_OCTET_DEFINED
#define DDS_SEQUENCE_OCTET_DEFINED
typedef struct dds_sequence_octet
{
  uint32_t _maximum;
  uint32_t _length;
  uint8_t *_buffer;
  bool _release;
} dds_sequence_octet;

#define dds_sequence_octet__alloc() \
((dds_sequence_octet*) dds_alloc (sizeof (dds_sequence_octet)));

#define dds_sequence_octet_allocbuf(l) \
((uint8_t *) dds_alloc ((l) * sizeof (uint8_t)))
#endif /* DDS_SEQUENCE_OCTET_DEFINED */

typedef struct unitree_api_msg_dds__Request_
{
  struct unitree_api_msg_dds__RequestHeader_ header;
  char * parameter;
  dds_sequence_octet binary;
} unitree_api_msg_dds__Request_;

extern const dds_topic_descriptor_t unitree_api_msg_dds__Request__desc;

#define unitree_api_msg_dds__Request___alloc() \
((unitree_api_msg_dds__Request_*) dds_alloc (sizeof (unitree_api_msg_dds__Request_)));

#define unitree_api_msg_dds__Request__free(d,o) \
dds_sample_free ((d), &unitree_api_msg_dds__Request__desc, (o))

#ifndef DDS_SEQUENCE_OCTET_DEFINED
#define DDS_SEQUENCE_OCTET_DEFINED
typedef struct dds_sequence_octet
{
  uint32_t _maximum;
  uint32_t _length;
  uint8_t *_buffer;
  bool _release;
} dds_sequence_octet;

#define dds_sequence_octet__alloc() \
((dds_sequence_octet*) dds_alloc (sizeof (dds_sequence_octet)));

#define dds_sequence_octet_allocbuf(l) \
((uint8_t *) dds_alloc ((l) * sizeof (uint8_t)))
#endif /* DDS_SEQUENCE_OCTET_DEFINED */

typedef struct unitree_api_msg_dds__Response_
{
  struct unitree_api_msg_dds__ResponseHeader_ header;
  char * data;
  dds_sequence_octet binary;
} unitree_api_msg_dds__Response_;

extern const dds_topic_descriptor_t unitree_api_msg_dds__Response__desc;

#define unitree_api_msg_dds__Response___alloc() \
((unitree_api_msg_dds__Response_*) dds_alloc (sizeof (unitree_api_msg_dds__Response_)));

#define unitree_api_msg_dds__Response__free(d,o) \
dds_sample_free ((d), &unitree_api_msg_dds__Response__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_RPC_H */
