/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: echo.h
  Source: /home/takara/work/keel/unitree-sdk-rs/crates/cyclonedds-sys/csrc/echo.idl
  Cyclone DDS: V0.10.2

*****************************************************************/
#ifndef DDSC_ECHO_H
#define DDSC_ECHO_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct cyclonedds_sys_test_Echo
{
  char * content;
  int32_t seq;
} cyclonedds_sys_test_Echo;

extern const dds_topic_descriptor_t cyclonedds_sys_test_Echo_desc;

#define cyclonedds_sys_test_Echo__alloc() \
((cyclonedds_sys_test_Echo*) dds_alloc (sizeof (cyclonedds_sys_test_Echo)));

#define cyclonedds_sys_test_Echo_free(d,o) \
dds_sample_free ((d), &cyclonedds_sys_test_Echo_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ECHO_H */
